#!/usr/bin/env sh

# Dropblox Supabase Setup Script
# Usage: ./setup-supabase.sh

echo "=== Dropblox Supabase Setup ==="
echo ""
echo "Prerequisites:"
echo "1. Supabase CLI installed: npm install -g supabase"
echo "2. Logged in: supabase login"
echo "3. Project created at https://app.supabase.com"
echo ""
echo "Steps to complete:"
echo ""
echo "1. Link your project:"
echo "   supabase link --project-ref YOUR_PROJECT_REF"
echo ""
echo "2. Run migrations:"
echo "   supabase db push"
echo ""
echo "3. Enable Discord OAuth:"
echo "   - Go to Authentication > Providers in Supabase Dashboard"
echo "   - Enable Discord provider"
echo "   - Add your Discord app's Client ID and Secret"
echo "   - Set redirect URL: https://YOUR_PROJECT.supabase.co/auth/v1/callback"
echo ""
echo "4. Copy environment variables to .env.local:"
echo "   NEXT_PUBLIC_SUPABASE_URL=https://YOUR_PROJECT.supabase.co"
echo "   NEXT_PUBLIC_SUPABASE_ANON_KEY=YOUR_ANON_KEY"
echo ""
echo "5. Install npm dependencies:"
echo "   npm install @supabase/supabase-js"
echo ""
echo "=== Setup Complete ==="
